serverspec->inspec (WIP)
osuosl-cookbooks/osl-docker pull request #36
Opened 2019-11-07 01:06 UTC by Vancelot11

2019-11-07 01:08 UTC, Vancelot11 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cookbooks not yet migrated to Inspec](https://trello.com/c/HR86dvVI/1386-cookbooks-not-yet-migrated-to-inspec)

2019-11-15 22:38 UTC, Vancelot11 commented
@ramereth I removed the packages that were creating conflicts from the recipes but there aren't any tests in the current integration to confirm that no functionality was lost. If you have time would you mind checking out this PR and maybe recommending a way to test that it's still behaving as expected without the dkms package or cuda drivers?

2019-11-18 19:48 UTC, ramereth commented
@Vancelot11 I fixed the issue in #37 so I recommend you rebase against that

2019-11-19 00:30 UTC, ramereth commented
@Vancelot11 can you squash the last two commits into one please?

2019-11-25 19:47 UTC, ramereth commented on recipes/nvidia.rb
> +# package %w(nvidia-driver-latest-dkms cuda-drivers nvidia-docker2)
I fixed this in #38 so if you rebase, this should be reverted back.

2019-11-25 22:58 UTC, ramereth requested changes

2019-11-25 22:58 UTC, ramereth commented on test/integration/nvidia/inspec/nvidia_spec.rb
> +# end
Please add this back.

2019-11-25 22:58 UTC, ramereth commented on test/integration/nvidia/inspec/nvidia_spec.rb
> +# end
Please add this back.

2019-11-27 01:02 UTC, ramereth approved these changes
Please merge as-is.

2019-12-02 21:15 UTC, merged