Upgrade docker-compose to 2.15
osuosl-cookbooks/osl-docker pull request #67
Opened 2023-01-06 19:26 UTC by pasimko

x86 is updated, powerpc still needs a build.

2023-01-06 20:27 UTC, ramereth requested changes
Please also fix/update the tests

2023-01-06 20:27 UTC, ramereth commented on attributes/compose.rb
>    default['osl-docker']['compose']['url_base'] = 'https://github.com/docker/compose/releases/download'
Please add `aarch64` binaries too.

2023-01-06 20:39 UTC, ramereth commented on attributes/compose.rb
>    default['osl-docker']['compose']['checksum'] = '4458de249ca5f776738e44a6af2f869c1186b2d018dd15705045aa01a45e50c5'
I just built a new version and pushed it up, please update the checksum to `2b57f69c438fadaa88dc383d8df8b98955a2ab9262c7ca2524102c8199c8efb4`

2023-01-10 00:34 UTC, ramereth requested changes
Please update the InSpec test.

2023-01-10 20:53 UTC, ramereth requested changes
You need to fix this following line: https://github.com/osuosl-cookbooks/osl-docker/blob/7cbd57c67b6b8e45818d719b85965fead549193f/recipes/compose.rb#L23

That line should be changed to the following:
```
source "#{compose['url_base']}/v#{compose['version']}/#{compose['filename']}"
```

2023-01-10 20:53 UTC, ramereth commented on test/integration/compose/inspec/compose_spec.rb
> +  its('stdout') { should match(/docker-compose version 2\.15\.0/) }
You need to fix the test to do the following.
```suggestion
  its('stdout') { should match(/docker-compose version v2\.15\.0/) }
```

2023-01-20 20:34 UTC, pasimko commented
```type=AVC msg=audit(1674242743.553:214): avc:  denied  { append } for  pid=5090 comm="newaliases" path="socket:[22505]" dev="sockfs" ino=22505 scontext=system_u:system_r:system_mail_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket permissive=0```
SELinux fails to install for compose-centos-stream-8 due to OOM, and when it does converge the SELinux integration test finds this error message.

2023-01-20 22:57 UTC, ramereth commented
@pasimko try increasing the size of the instance first to work around the OOM issue

2023-01-25 20:01 UTC, ramereth commented
!bump minor ~

2023-01-25 20:01 UTC, merged

2023-01-25 20:02 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.7.0.  Have a nice day!