AlmaLinux 9 Support
osuosl-cookbooks/osl-docker pull request #77
Opened 2024-06-27 20:32 UTC by sharoninator

2024-07-01 21:27 UTC, ramereth commented
@sharoninator can you please rebase and resolve the conflicts?

2024-07-04 01:29 UTC, ramereth requested changes

2024-07-04 01:29 UTC, ramereth commented on test/integration/inspec/controls/default_spec.rb
> +>>>>>>> fc70022 (Added almalinux 9)
This was missed when you did your rebase. Please fix and squash your commits.

2024-07-09 14:12 UTC, ramereth requested changes
Please add AlmaLinux 9 to spec tests.

2024-08-26 22:28 UTC, ramereth commented
!bump patch ~

2024-08-26 22:28 UTC, merged

2024-08-26 22:28 UTC, osuosl-manatee commented
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v4.14.1.  Have a nice day!